config/routes.rb
Rails.application.routes.draw do
  get 'reports', to: 'reports#index'
  get 'report_by_category', to: 'reports#report_by_category'
  get 'report_by_dates', to: 'reports#report_by_dates'
  post 'report_by_category', to: 'reports#report_by_category'
  post 'report_by_dates', to: 'reports#report_by_dates'
  resources :operations
  resources :categories
  root "main#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :name, presence: true
  has_many :operations
end

app/models/operation.rb
class Operation < ApplicationRecord
  validates :amount, presence: true, numericality: { greater_than: 0 }
  validates :description, presence: true
  validates :odate, presence: true
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name, :description)
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/operations_controller.rb
class OperationsController < ApplicationController
  before_action :set_operation, only: %i[ show edit update destroy ]

  # GET /operations or /operations.json
  def index
    @operations = Operation.all
  end

  # GET /operations/1 or /operations/1.json
  def show
  end

  # GET /operations/new
  def new
    @operation = Operation.new
  end

  # GET /operations/1/edit
  def edit
  end

  # POST /operations or /operations.json
  def create
    @operation = Operation.new(operation_params)

    respond_to do |format|
      if @operation.save
        format.html { redirect_to operation_url(@operation), notice: "Operation was successfully created." }
        format.json { render :show, status: :created, location: @operation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @operation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /operations/1 or /operations/1.json
  def update
    respond_to do |format|
      if @operation.update(operation_params)
        format.html { redirect_to operation_url(@operation), notice: "Operation was successfully updated." }
        format.json { render :show, status: :ok, location: @operation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @operation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /operations/1 or /operations/1.json
  def destroy
    @operation.destroy

    respond_to do |format|
      format.html { redirect_to operations_url, notice: "Operation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_operation
      @operation = Operation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def operation_params
      params.require(:operation).permit(:amount, :odate, :spend, :description, :category_id)
    end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def index
  end

  def report_by_category
    if params[:id].blank?
      collection = Operation.where(spend: params[:spend], odate: (params[:start_date]..params[:end_date])).group(:odate).sum(:amount)
    else
      collection = Operation.where(category_id: params[:id])
      collection = collection.where(spend: params[:spend], odate: (params[:start_date]..params[:end_date])).group(:odate).sum(:amount)
    end

    @operations = collection.map{ |k,v| k.to_s}
    @categories = collection.values
  end


  def report_by_dates
    collection = Operation.where(spend: params[:spend], odate: (params[:start_date]..params[:end_date])).group(:odate).sum(:amount)

    @dates = collection.map{ |k,v| k.to_s}
    @amount = collection.values
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def top_categories
    top_categories = Category.all.sort_by { |category| category.operations.count }.reverse.last(3)
  end
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/operations_helper.rb
module OperationsHelper
  def recent_expenses
    Operation.where(spend: false).first(3)
  end
  def recent_income
    Operation.where(spend: true).first(3)
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>" class="card mb-3">
  <div class="card-body">
    <p class="card-title">
      <b>Name: </b><%= category.name %>
    </p>
    <p class="card-title">
      <b>Description: </b><%= category.description %>
    </p>
  </div>
</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3 mt-4 row">
    <div class="col-sm-1 col-form-label">
      <strong><%= form.label :name %></strong>
    </div>

    <div class="col-sm-9">
      <%= form.text_field :name, autocomplete: "Name", class: 'form-control form-control-lg'  %>
    </div>
  </div>
  <br>


  <div class="mb-3 mt-4 row">
    <div class="col-sm-1 col-form-label">
      <strong><%= form.label :description %></strong>
    </div>

    <div class="col-sm-9">
      <%= form.text_field :description, autocomplete: "Description", class: 'form-control form-control-lg'  %>
    </div>
  </div>
  <br>

  <div>
    <%= form.submit class: 'btn btn-dark' %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category, class: "btn btn-dark" %>
  <%= link_to "Back to categories", categories_path, class: "btn btn-dark" %>
</div>

app/views/categories/index.html.erb
<p class="text-success"><%= notice %></p>

<h1>Categories</h1>

<div class="mt-3" id="categories">
  <% @categories.each do |c| %>
    <%= render 'category', category: c %>

    <div class="mb-3">
      <%= link_to "Show this category", c, class: "btn btn-dark" %>
      <%= link_to "Edit this category", edit_category_path(c), class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

<%= link_to "New category", new_category_path, class: "btn btn-success" %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Back to categories", categories_path, class: "btn btn-dark" %>
</div>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<div id="<%= dom_id @category %>" class="mb-3">
  <h4><b>Name: </b><%= @category.name %></h4>
  <h4><b>Description: </b><%= @category.description %></h4>
</div>

<div>
  <div class="mb-1">
    <%= link_to "Edit this category", edit_category_path(@category), class: "btn btn-dark" %>
    <%= link_to "Back to categories", categories_path, class: "btn btn-dark" %>
  </div>
  <%= button_to "Destroy this category", @category, method: :delete, class: "btn btn-danger" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PFM</title>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container-flouid">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">
            <h3>PFM</h3>
          </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <%=link_to 'Home', root_path, class: 'nav-link active' %>
              </li>
              <li class="nav-item">
                <%=link_to 'Operations', operations_path, class: 'nav-link active' %>
              </li>
              <li class="nav-item">
                <%=link_to 'Categories', categories_path, class: 'nav-link active' %>
              </li>
              <li class="nav-item">
                <%=link_to 'Reports', reports_path, class: 'nav-link active' %>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </div>
    <div class="container mt-3">
      <%= yield %>
    </div>
    <footer class="flex-shrink-0 mt-3 py-4 bg-dark text-white-50">
      <div class="container text-center">
        <small>KUVIRLIK &copy; PFM</small>
      </div>
    </footer>
  </body>
</html>

app/views/main/index.html.erb
<div class="row">
  <div class="col-md-6">
    <div class="card">
      <div class="card-header">
        <h5 class="card-title">Recent income</h5>
      </div>
      <div class="card-body">
        <table class="table">
          <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Amount</th>
            <th scope="col">Date</th>
            <th scope="col">Show</th>
          </tr>
          </thead>
          <tbody>
          <% recent_income.each_with_index do |ri, i|%>
            <tr>
              <th scope="row"><%= i + 1 %></th>
              <td><%= ri.amount %></td>
              <td><%= ri.odate.strftime("%d.%m.%Y %k:%M") %></td>
              <td><%= link_to 'Show', operation_path(ri), class: 'btn btn-dark' %></td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <div class="col-md-6">
    <div class="card">
      <div class="card-header">
        <h5 class="card-title">Recent expenses</h5>
      </div>
      <div class="card-body">
        <table class="table">
          <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Amount</th>
            <th scope="col">Date</th>
            <th scope="col">Show</th>
          </tr>
          </thead>
          <tbody>
            <% recent_expenses.each_with_index do |re, i|%>
            <tr>
              <th scope="row"><%= i + 1 %></th>
              <td><%= re.amount %></td>
              <td><%= re.odate.strftime("%d.%m.%Y %k:%M") %></td>
              <td><%= link_to 'Show', operation_path(re), class: 'btn btn-dark' %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<div class="card mt-4">
  <div class="card-header">
    <h5 class="card-title">Top categories</h5>
  </div>
  <div class="card-body">
    <table class="table">
      <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Operations</th>
        <th scope="col">Show</th>
      </tr>
      </thead>
      <tbody>
      <% top_categories.each_with_index do |tc, i|%>
        <tr>
          <th scope="row"><%= i + 1 %></th>
          <td><%= tc.name %></td>
          <td><%= tc.operations.count %></td>
          <td><%= link_to 'Show', category_path(tc), class: 'btn btn-dark' %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/operations/_form.html.erb
<%= form_with(model: operation) do |form| %>
  <% if operation.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(operation.errors.count, "error") %> prohibited this operation from being saved:</h2>

      <ul>
        <% operation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :amount, style: "display: block" %>
    <%= form.text_field :amount %>
  </div>

  <div>
    <%= form.label :odate, style: "display: block" %>
    <%= form.datetime_field :odate %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :category_id, style: "display: block" %>
    <%= form.collection_select :category_id, Category.all, :id, :name %>
  </div>

  <div class="form-check form-check-inline">
    <%= label :spend, "Витрата", value: true %>
    <%= form.radio_button :spend, false, :checked => true, :value => false, class: "form-check-input" %>
  </div>
  <div class="form-check form-check-inline">
    <%= label :spend, "Дохід", value: false %>
    <%= form.radio_button :spend, true, :value => true, class: "form-check-input" %>
  </div>



  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/operations/_operation.html.erb
<div id="<%= dom_id operation %>">
  <p>
    <strong>Amount:</strong>
    <%= operation.amount %>
  </p>

  <p>
    <strong>Odate:</strong>
    <%= operation.odate.strftime("%d.%m.%Y %k:%M") %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= operation.description %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= operation.category_id %>
  </p>

</div>

app/views/operations/edit.html.erb
<h1>Editing operation</h1>

<%= render "form", operation: @operation %>

<br>

<div>
  <%= link_to "Show this operation", @operation, class: "btn btn-dark" %>
  <%= link_to "Back to operations", operations_path, class: "btn btn-dark" %>
</div>

app/views/operations/index.html.erb
<p class="text-success"><%= notice %></p>

<h1>Operations</h1>

<div class="mt-3" id="operations">
  <% @operations.each do |operation| %>
    <div id="<%= dom_id operation %>" class="card mb-3">
      <div class="card-body">
        <p class="card-text">
          <strong>Amount:</strong>
          <%= operation.amount %>
        </p>

        <p class="card-text">
          <strong>Odate:</strong>
          <%= operation.odate.strftime("%d.%m.%Y %k:%M") %>
        </p>

        <p class="card-text">
          <strong>Description:</strong>
          <%= operation.description %>
        </p>

        <p class="card-text">
          <strong>Type:</strong>
          <% if operation.spend %>
            Income
          <% else %>
            Expense
          <% end %>
        </p>

        <p class="card-text">
          <strong>Category:</strong>
          <%= operation.category.name %>
        </p>

      </div>
      <p>
        <%= link_to "Show this operation", operation, class: "btn btn-dark" %>
      </p>
    </div>
  <% end %>
</div>

<%= link_to "New operation", new_operation_path, class: "btn btn-success" %>

app/views/operations/new.html.erb
<h1>New operation</h1>

<%= render "form", operation: @operation %>

<br>

<div>
  <%= link_to "Back to operations", operations_path, class: "btn btn-dark" %>
</div>

app/views/operations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @operation %>

<div>
  <div class="mb-1">
    <%= link_to "Edit this operation", edit_operation_path(@operation), class: "btn btn-dark" %>
    <%= link_to "Back to operations", operations_path, class: "btn btn-dark" %>
  </div>

  <%= button_to "Destroy this operation", @operation, method: :delete, class: "btn btn-danger" %>
</div>

app/views/reports/_report_by_form.html.erb
<%= form_tag type, method: :get, data: { turbo: "false" } do %>
  <% if type == report_by_category_path %>
    <%= select_tag("id", options_for_select(Category.all.map{ |u| [ u.name, u.id ] }, params[:id]), include_blank: "All categories", class: "form-select") %>
  <% end %>
  <div>
    <%= label :start_date, "Date from:" %>
    <%= date_field_tag 'start_date', Date.today, class: 'form-control' %>
  </div>
  <div>
    <%= label :end_date, "Date to:" %>
    <%= date_field_tag 'end_date', Date.today, class: 'form-control' %>
  </div>
  <br>
  <div class="form-check form-check-inline">
    <%= radio_button_tag :spend, 1, false %>
    <%= label :spend, "Income", value: true %>
  </div>
  <div class="form-check form-check-inline">
    <%= radio_button_tag :spend, 0, true %>
    <%= label :spend, "Expense", value: false %>
  </div>
  <hr>
  <%= submit_tag 'Generate', class: 'btn btn-dark' %>
<% end %>

app/views/reports/index.html.erb
<div class="row">
  <div class="col-sm-6">
    <div class="card">
      <div class="card-header">
        <h5 class="card-title">Report by categories</h5>
      </div>
      <div class="card-body">
        <p class="card-text">
          <%= render 'report_by_form', type: report_by_category_path %>
        </p>
      </div>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="card">
      <div class="card-header">
        <h5 class="card-title">Report by dates</h5>
      </div>
      <div class="card-body">
        <p class="card-text">
          <%= render 'report_by_form', type: report_by_dates_path %>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/reports/report_by_category.html.erb
<div class="card text-center">
  <div class="card-header">
    <h5 class="card-title">Category: <%= params["id"].blank? ? 'All categories' : Category.find_by(id: params["id"]).name %></h5>
    <h5 class="card-title">Date from: <%= params["start_date"]%> to: <%= params["end_date"] %></h5>
  </div>
  <div class="card-body">
    <canvas id="lineChart"></canvas>
  </div>
</div>
<%=link_to 'Back', :back, class: 'btn btn-dark mt-3' %>

<script>

  const data = {
    labels: <%= raw  @operations %>,
    datasets: [
      {
        label: 'UAH',
        data: <%= raw @categories %>,
        backgroundColor: 'rgba(75, 192, 192, 0.2)', // Optional
        borderColor: 'rgba(75, 192, 192, 1)', // Optional
        borderWidth: 1 // Optional
      }
    ]
  };

  // Chart configuration
  const config = {
    type: 'line',
    data: data,
    options: {
      responsive: true,
      scales: {
        y: {
          beginAtZero: true
        }
      }
    }
  };

  // Create the chart
  const lineChart = new Chart(document.getElementById('lineChart'), config);
</script>

app/views/reports/report_by_dates.html.erb
<div class="card text-center">
  <div class="card-header">
    <h5 class="card-title">Date from: <%= params["start_date"] %> to: <%= params["end_date"] %></h5>
  </div>
  <div class="card-body">
    <canvas id="lineChart"></canvas>
  </div>
</div>
<%=link_to 'Back', :back, class: 'btn btn-dark mt-3' %>
<script>

  document.addEventListener('DOMContentLoaded', function () {
    const data = {
      labels: <%= raw @dates %>,
      datasets: [
        {
          label: 'UAH',
          data: <%= raw @amount %>,
          backgroundColor: 'rgba(75, 192, 192, 0.2)', // Optional
          borderColor: 'rgba(75, 192, 192, 1)', // Optional
          borderWidth: 1 // Optional
        }
      ]
    };

    // Chart configuration
    const config = {
      type: 'line',
      data: data,
      options: {
        responsive: true,
        scales: {
          y: {
            beginAtZero: true
          }
        }
      }
    };

    // Create the chart
    const lineChart = new Chart(document.getElementById('lineChart'), config);
  })
</script>